### ISSUE TITLE
Armor rebalance, more relic and mana potions  

### ISSUE THREAD

**Issue by KaykenJr** [iron431/Irons-Spells-n-Spellbooks#109]
### Feature description

Reducing the amount of armor protection that the armor the mod provides, Adding more relics with niche use for specific spells and other relics for more common goals and Lastly adding mana regeneration potion (which temporarily increase the speed of which your mana is regenerated) and + max mana potions (which temporarily increase your max mana capacity)

### How it improves the player experience

Currently when playing with the mod i always skip most of the armor in vanilla and go strait for the mods cheapest to make armor because it gives roughly the same protection as netherite and is much more easily obtainable in the early game. This is a problem because this makes vanilla armor basically useless i think that the mods armor should be a trade off of less protection for more magic offensive capacity and making relics very rare and niche artifacts that can make it so you have lots of protection and magic capacity for the trade off that its very rare to find and for mid game potions can be used for temporary advantages.

**Comment by iron431** [comment]
Basic mana potions will be coming very soon. Other potions may come later.

The school armor actually does have less overall protection that netherite, quite significantly in fact. This is due to the armor toughness stat. In fact, it even has less damage reduction than diamond. It being "easier" to obtain than diamond is also likely 
 not true, considering diamond armor can be found in various structures, vanilla or modded. And even then, finding a few diamond to  craft a piece of diamond armor will be easier than finding stacks of essence, a rune, and 8 focuses for a single piece of school armor.
