### ISSUE TITLE
Add guidebook text to language file

### ISSUE THREAD

**Issue by SAGA23456** [iron431/Irons-Spells-n-Spellbooks#155]
### Feature description

I am Japanese and wanted to make this MOD easier to understand for Japanese users, so I created a Japanese translation file. However, even after translating everything, the contents of the guidebook could not be translated.

### How it improves the player experience

I would like them to add a program to translate the guidebook to the language file.

**Comment by iron431** [comment]
I'm not sure I understand the request, but if you're asking how to translate the patchouli book, you can view their wiki here: https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/getting-started
Otherwise, I do not know japanese and won't be working on this

**Comment by ultimateconclusion** [comment]
Sorry for bothering to email you. Well, I made a slight typo. To be more precise, I would like en_us, the source of the language files, to add a translation of the guidebook (Japanese translation will be done here)
Windows の メ`ル<https://go.microsoft.com/fwlink/?LinkId=550986> から送信

差出人: ***@***.***>
送信日r: 2023年9月13日 8:31
宛先: ***@***.***>
CC: ***@***.***>; ***@***.***>
件名: Re: [iron431/Irons-Spells-n-Spellbooks] Add guidebook text to language file (Issue #155)


I'm not sure I understand the request, but if you're asking how to translate the patchouli book, you can view their wiki here: https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/getting-started
Otherwise, I do not know japanese and won't be working on this

―

**Comment by ultimateconclusion** [comment]
Sorry for bothering to email you. Well, I made a slight typo. To be more precise, I would like en_us, the source of the language files, to add a translation of the guidebook (Japanese translation will be done here)

**Comment by SAGA23456** [comment]
I created it and sent it to Discord DM.
