### ISSUE TITLE
[Bug] bypassing not being able to identify unlearned scrolls

### ISSUE THREAD

**Issue by Sketano** [iron431/Irons-Spells-n-Spellbooks#235]
### Observed behaviour

<img width="960" alt="image" src="https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/124691491/55fa3f9e-218c-4fce-836a-ffce460f3622">

You can use JEI to check the description of the scroll, also you can see the icon of the spell

I am using the Curio Casting Snapshot if it matters

### Expected behaviour

not be able to see it

### Steps to reproduce

1. Go in game
2. get an unlearned eldritch spell
3. use jei on it

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.1-SNAPSHOT

### Forge version

1.20.1-47.2.6

**Comment by iron431** [comment]
being able to see the icons is intentional, so the player can know which spell to learn if they have a scroll. likewise, jei showing the description is not an issue. its already on the wiki - if you want to play the game blind, jei isn't the mod for you. plus jei doesn't allow for dynamic descriptions anyways.
