### ISSUE TITLE
[Bug] Capturing and Releasing a Necromancer crashes the client

### ISSUE THREAD

**Issue by TronWoWGamer** [iron431/Irons-Spells-n-Spellbooks#279]
### Observed behaviour

I used a mob yoinker from Utilitix to capture a Necromancer.  Then I went to my mob farm and released the Necromancer so the mob farm could kill it.  The client crashed when I tried to click the yoinker and release the Necromancer.

Error: java.lang.ClassCastException: class com.farsight.FarsightClientChunkManager cannot be cast to class net.minecraft.server.level.ServerChunkCache (com.farsight.FarsightClientChunkManager is in module farsight_view@1.20.1-3.6 of loader 'TRANSFORMER' @66a50c93; net.minecraft.server.level.ServerChunkCache is in module minecraft@1.20.1 of loader 'TRANSFORMER' @66a50c93)

### Expected behaviour

I expected the Necromancer to appear in front of me just like any other mob I have captured/released with a mob yoinker.

### Steps to reproduce

1. craft a mob yoinker
2. nab (capture) a necromancer with yoinker
3. release necromancer from yoinker

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.1.2

### Forge version

47.2.19

### Other mods

This is ATM9 version 0.2.35

**Comment by TronWoWGamer** [comment]
**Update 1:** restarted my client and tried again, to see if it was a fluke, and it happened again, same thing, same error.  I am just going to delete the yoinker/necromancer then give myself a spawn egg (if possible), use a mob imprisonment tool from Industrial Foregoing, and see if the same thing happens.

**Update 2:** gave myself a spawn egg for the Necromancer and a mob imprisonment tool from Industrial Foregoing. 
- spawned necromancer with egg
- captured necromancer with pokey ball
- released necromancer
- no crash

**Comment by lab3** [comment]
Based on the error you posted the issue is in farsight.  You can report it to them.   If you have a full crashlog I could take a deeper look but this doesn't appear to be an issue on our side. 

https://github.com/someaddons/farsight/issues

**Comment by SenojLuap** [comment]
Had this crash occur to me today, with the same steps taken and same results. Full logs are available here: https://mclo.gs/0Pjb2Yt
I've posted this same crash to the Farsight repo in case it's on their end: https://github.com/someaddons/farsight/issues/92

**Comment by someaddons** [comment]
@lab3 Reposting what I wrote on the farsight issue, so you see it:

Looks like an issue of utilix and irons spells n spellbooks, trying to cast the clientside chunk manager to ServerChunkCache on render thread seems wrong.

It seems the issue is triggered from utilix loading and creating the mob on client side: https://github.com/MelanX/UtilitiX/blob/6f11ba08ce54b4a1e69c84fb42af1f6d5e2cf088/src/main/java/de/melanx/utilitix/item/ItemMobYoinker.java#L42

Which in turn triggers Irons spells n spellbooks to call its "sync to client" which is expected to run on the serverside not the clientside.
Even without farsight this will crash as you cannot cast to "ServerChunkCache" on the client side
