### ISSUE TITLE
Option to disable giving new players the book

### ISSUE THREAD

**Issue by johalun** [iron431/Irons-Spells-n-Spellbooks#312]
### Feature description

For modpacks that provide an Akashic Tome that include all books and manuals from mods, it would be very useful to be able to disable giving player a copy of the book when joining a new world.

### How it improves the player experience

Avoiding giving players a book that's already included in the Akashic Tome.

**Comment by iron431** [comment]
you can do this with a datapack

**Comment by Vaelzan** [comment]
For those who happen to come here later and want to see how to change it, it has been implemented as an advancement, which wasn't clear until I saw that reply (as it differs from how mods typically handle starting books - most Forge mods still use TOML configs for adjusting that). Could I suggest adding this (or similar) information to your wiki so that it's actually documented somewhere?

Create a file with this path: `data/irons_spellbooks/advancements/grant_patchouli.json`, containing this JSON: `{criteria:{"impossible":{"trigger":"minecraft:impossible"}}}`. This will disable the advancement cleanly.
