### ISSUE TITLE
[Bug] Using Carry On to pick up Alchemist Cauldron causes infinite duplication glitch / player lock

### ISSUE THREAD

**Issue by goldrat1** [iron431/Irons-Spells-n-Spellbooks#404]
### Observed behaviour

When you shift-right click on a block entity with the Carry On mod installed, you pick it up and place it with a right-click.
When you shift-right click on an Alchemist Cauldron, you pick it up and can place it down again, but the cauldron doesn't actually leave your hands. So you can place it down again, and again, forever. 
This also disables your inventory and any way to interact with the environment so it essentially locks the player until they clear the item they're holding with commands.

### Expected behaviour

Right-clicking after picking up the cauldron should just place it down once.

### Steps to reproduce

1. Install Carry On
2. Install Iron's Spellbooks
3. Shift-right-click on an Alchemist Cauldron to pick it up
4. Right click to place down Cauldron and duplicate it.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.3

### Forge version

1.20.1 - 47.2.23

### Other mods

Carry On, 1.20.1 v2.1.2.7

**Comment by iron431** [comment]
This is a known carry on issue and should be reported to them

**Comment by ThomasNikoy** [comment]
I think i had the same issue. It took a while to figure out what to do. Dying was the "easiest" solution but with the keepInventory feature set on TRUE i couldn't do it. So i turned the feature on FALSE by typing /gamerule keepInventory false and it worked.
Hope this helps!!

**Comment by JasdanVM** [comment]
Can confirm this still happens in the latest 1.20.1 version.

**Comment by iron431** [comment]
> This is a known carry on issue and should be reported to them

https://github.com/Tschipp/CarryOn/issues/674

**Comment by kenkengo1020** [comment]
This issue appears to be caused by Carry On trying to pick up a complex tile entity that is not compatible with being carried.

✔ Workaround (Solution)

You can prevent Carry On from picking up the Alchemist Cauldron by adding it to the mod’s blacklist.

In the carryon-common.toml config file, add:

forbiddenTiles = ["#forge:immovable", "irons_spellbooks:alchemist_cauldron"


This successfully blocks Carry On from interacting with the Alchemist Cauldron, preventing the duplication glitch and the player-lock bug.
