### ISSUE TITLE
A new Spell called Possession

### ISSUE THREAD

**Issue by Greg727** [iron431/Irons-Spells-n-Spellbooks#427]
### Feature description

A spell that allows a player to possess a mob for a short period of time 

Think spectator mode's function of possessing a mob, but allows the player to control the mob's movements

### How it improves the player experience

It allows the player to navigate the world using mobs and their various ways of traveling, like possessing the phantom and flying around

**Comment by FuryJack07** [comment]
This sounds so fun! long cooldown, 5 sec cast time, health percentage cap (if the current target's health is below X% it works, otherwise it fails) and limited duration

Level increses health cap (9% of max Hp per level) and the duration (2 minute per level) with 10 levels!

always legentady, Eldrich spell, and generic spell power increses only increse the duration

this doesn't seem overpowered because of the health percentage being 90 at maximum level with no way of getting it higher othen than a ring of affinity, which are already rare by themselves, even more for eldrich spells, and still there being a 1/7 chance of it being the spell you want

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
