### ISSUE TITLE
[Bug] Entity Culling Incompatability with Planar Sight

### ISSUE THREAD

**Issue by ghost** [iron431/Irons-Spells-n-Spellbooks#499]
### Observed behaviour

Entities stop rendering even with the Planar Sight effect enabled.

This behavior was reported to Entity Culling's github but they mentioned the only way to fix this is to use the "entity culling api" to disable "culling for these 'custom glowing' entities so entity culling ignores them" (https://github.com/tr7zw/EntityCulling/issues/163#issuecomment-2231815860).

### Expected behaviour

Entities render through blocks.

### Steps to reproduce

Install Entity Culling [(https://www.curseforge.com/minecraft/mc-mods/entityculling)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
Install Iron's Spellbooks
Use Planar Sight
Observe that it only works when directly staring at an entity.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.2.1

### Forge version

47.2.32

### Other mods

The mod list is huge but my modpack is on curseforge: [https://www.curseforge.com/minecraft/modpacks/the-greediest-wish/files/5536526/dependencies](https://www.curseforge.com/minecraft/modpacks/the-greediest-wish/files/5536526/dependencies)

**Comment by iron431** [comment]
I am likewise bouncing this issue back to them, because their implementation is not ideal. It is also not my responsibility to "have compile-time dependencies and code for specific mod" due to them changing vanilla mechanics. See a more detailed response here: https://github.com/tr7zw/EntityCulling/issues/163#issuecomment-2231847139
