### ISSUE TITLE
[Bug] ISS Guidebook isn't visible in JEI

### ISSUE THREAD

**Issue by jangro** [iron431/Irons-Spells-n-Spellbooks#545]
### Observed behaviour

The Iron Spells Guide Book is not visible in JEI. It has a recipe and can be crafted, but no matter how I search I cannot find it.

Also searched with @iron and @patchouli and it doesn't appear. 

### Expected behaviour

search JEI. Find the guide book. 

### Steps to reproduce

Open JEI
Search for guide or @iron or @patch
No book

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.4.0

### Forge version

1.20.1 - 47.3.0

### Other mods

Player Animator [1.0.2-rc1+1.20] 
Patchouli [1.20.1-84-FORGE ] 
GeckoLib 4 [4.4.7] 
Curios API [5.9.1+1.20.1 ] 
Caelus API [3.2.0+1.20.1] 
Just Enough Items [15.12.3.54]

**Comment by Saereth** [comment]
seconding this on MC 1.21.1 Neoforge 21.1.31

if I spawn in a patchouli book and nbtedit it to irons_spellbooks:iss_guide_book the book exists but no way to see it in jei/creative menu and the book also doesnt currently fully load due to a patchouli error on page 8

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/92b2d82b-90d4-4afe-959b-1ec24543f1fc">

**Comment by dainekoichi** [comment]
Same is also happening on my end; I can't find it via JEI, but there's a recipe with a broken result:
![image](https://github.com/user-attachments/assets/6389146c-bd72-4829-a72b-9ca630d55062)

**Comment by iron431** [comment]
patchouli compat was ported a few versions ago
