### ISSUE TITLE
[Suggest]Request to Change Supported Curios Mod

### ISSUE THREAD

**Issue by Huaranyue** [iron431/Irons-Spells-n-Spellbooks#591]
### Feature description

Adorned is not an officially supported mod by Curios, and it has several bugs. For example, it is unable to modify the accessory slots using normal commands, and adding accessory slots causes misaligned icons. Please consider updating the support to Curios API Continuation, which is an actively maintained mod with frequent bug fixes.

### How it improves the player experience

I really appreciate your creations and hope that Iron's Spells 'n Spellbooks continues to get better.

**Comment by iron431** [comment]
neither are official

**Comment by iron431** [comment]
apparently curios api continuation also does not have a working command. without a material reason to switch, i will continue using the status quo

**Comment by IdrisQe** [comment]
It would probably be awkward to switch APIs, but maybe the Accessories API (https://modrinth.com/mod/accessories) could be used instead for 1.21? I feel like it's going to see more and more use by a lot of mods as it evolves, especially since it works for both NeoForge and Fabric, so mods which are released on both won't need to support one or both Curios continuations and Trinkets.

**Comment by iron431** [comment]
> without a material reason to switch, i will continue using the status quo
