### ISSUE TITLE
[Bug] Optifine breaks 1.20.1 Armor Textures

### ISSUE THREAD

**Issue by Anskotans** [iron431/Irons-Spells-n-Spellbooks#82]
### Observed behaviour

All textures worked fine except the armor textures. Tried all of the usual fixes like turning emissive textures and anisotropic filtering off but not luck. Even attempted to run it through forge 47.0.35 as well.

### Expected behaviour

Expected no issues.

### Steps to reproduce

1. Use Forge 47.0.50
2. Use Optifine pre9
3. Launch game with any of the mage armors.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.6.2.jar

### Forge version

47.0.35, 47.0.50

**Comment by Anskotans** [comment]
Maybe the mod is meant to run through an older version than 47.0.35? My players want to flex their drip while casting spells into god rays.

**Comment by Anskotans** [comment]
I didn't mean to close this

**Comment by iron431** [comment]
I've seen this before. Still not sure if it's our fault or optifines fault, and whether or not we will fix it on our end. In the meantime, I suggest using the Oculus/Rubidium mods instead of Optifine while playing modded anyways. Optifine was meant to be a standalone client, whereas Oculus and Rubidium implement shader support and most performance fixes optifine did anyways without breaking tons of mods.

**Comment by Anskotans** [comment]
I'll give that a shot, thank you for the quick response and great mod!
